name: ColimaUI
options:
  bundleIdPrefix: com.colimaui
  deploymentTarget:
    macOS: "14.0"
  xcodeVersion: "15.0"
  generateEmptyDirectories: true

settings:
  base:
    SWIFT_VERSION: "5.9"
    MACOSX_DEPLOYMENT_TARGET: "14.0"

targets:
  ColimaUI:
    type: application
    platform: macOS
    sources:
      - path: ColimaUI
        excludes:
          - "**/.DS_Store"
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.colimaui.app
        PRODUCT_NAME: ColimaUI
        INFOPLIST_FILE: ColimaUI/Info.plist
        CODE_SIGN_ENTITLEMENTS: ColimaUI/ColimaUI.entitlements
        CODE_SIGN_STYLE: Automatic
        DEVELOPMENT_TEAM: ""
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        ENABLE_HARDENED_RUNTIME: NO
        CODE_SIGN_IDENTITY: "-"
        COMBINE_HIDPI_IMAGES: YES
